name = 'Kubeflow'
license = 'MIT'
licenselink = 'https://github.com/davidgs/kubeflow-hugo/blob/master/LICENSE'
description = 'A modern, developer-focused Hugo theme for machine learning and Kubernetes projects'

# The home page of the theme, where the source can be found
homepage = 'https://kubeflow.org/'

# If you have a running demo of the theme
demosite = 'https://kubeflow.org/'

# Taxonomy terms
tags = ['machine-learning', 'kubernetes', 'developer', 'modern', 'responsive', 'dark-mode']
features = ['responsive', 'dark-mode', 'animations', 'code-highlighting', 'tailwind']

# If the theme has a single author
[author]
  name = 'Kubeflow Community'
  homepage = 'https://kubeflow.org/community/'
